#!/bin/sh

getscriptdir()
{
        cd "$(dirname "${0}")"
        echo "$PWD"
}

scriptdir="$(getscriptdir)"

if test "$1"; then
if [ "$1" = "install" ]; then
echo "\
[Desktop Entry]
Name=Rewinder
Exec="sh -c $(echo -n '"exec ';echo -n '"'; echo -n "$scriptdir/launch-xdg-wrap"; echo -n '"';echo -n '"')" %u
Icon=xterm
Type=Application
Terminal=false
StartupNotify=false
MimeType=x-scheme-handler/austiblox;
" > ~/.local/share/applications/rewinder.desktop
echo "Installed Rewiner."
elif [ "$1" = "uninstall" ]; then
rm ~/.local/share/applications/rewinder.desktop
echo "Uninstalled Rewiner."
fi
else
echo "Usage: $0 [install/uninstall]"
fi
