#!/bin/sh

getscriptdir()
{
        cd "$(dirname "${0}")"
        echo "$PWD"
}

scriptdir="$(getscriptdir)"

if test "$1"; then
	if [ "$1" = "install" ]; then
		if echo "$scriptdir" | grep -q ' '; then
			echo "If you have extracted this to a folder with a space, too bad."
			echo "Sorry, I have found no way to treat folders with spaces in"
			echo ".desktop files without xdg-open complaining so you have to"
			echo "extract this to a folder without a space."
			exit 1
		else
			echo "\
[Desktop Entry]
Name=Rewiner
Exec="$scriptdir/launch-xdg-wrap" %u
Icon=xterm
Type=Application
Terminal=false
StartupNotify=false
MimeType=x-scheme-handler/austiblox;
" > ~/.local/share/applications/austiblox.desktop
			echo "Installed Rewiner."
		fi
	elif [ "$1" = "uninstall" ]; then
		rm ~/.local/share/applications/austiblox.desktop
		echo "Uninstalled Rewiner"
	fi
else
		echo "Usage: $0 [install/uninstall]"
fi


