#!/bin/sh

getscriptdir()
{
        cd "$(dirname "$0")"
        echo "$PWD"
}

scriptdir="$(getscriptdir)"
WINEPREFIX="$scriptdir/wineprefix"
echo "$WINEPREFIX"

if ! test -f "$WINEPREFIX/RewinderInstalled"; then
	"$scriptdir/launch" "$*"
	"$scriptdir/launch" "$*"
else
	"$scriptdir/launch" "$*"
fi
