#!/bin/sh

# - Set wine options

getscriptdir()
{
        cd "$(dirname "${0}")"
        echo "$PWD"
}

scriptdir="$(getscriptdir)"
export DXVK_HUD=1
export WINEARCH=win32

export WINEPREFIX="$scriptdir/wineprefix"

# Use this if you want to use another Wine version/fork/whatever
export PATH="$HOME/.local/share/grapejuice/user/wine-download/wine-tkg-staging-fsync-git-7.20.r1.gbd2608b1/bin:$PATH"

#export MESA_GL_VERSION_OVERRIDE=4.5


hashtagcat()
{
	while IFS= read -r line; do
		echo "#${line}" || break
	done;kill -USR1 $yadpid
}

loadscreen()
{
	PLUG="$( od -An -N2 -tu2 /dev/urandom | tr -d ' ')"

	yad --class="rewiner-installer" --name="rewiner-installer" --window-icon="exec" \
	--center --no-buttons \
	--title="Rewiner Installer" \
	--borders=0 \
	--paned --tab=1 --tab=2 --key=$PLUG \
	--image "$scriptdir/banner.png" --image-on-top & yadpid="$!"

	yad --borders=0 --tabnum=1 --plug="$PLUG" --text-align=right --no-buttons --title=Rewiner &

	hashtagcat | \
	(yad --borders=5 \
	--tabnum=2 --plug="$PLUG" \
	--text-align=right \
	--no-buttons \
	--text='"'"i can fucking m*sturbate to make cheese"'"\n - josephtheguy      ' \
	--progress --pulsate --auto-close --enable-log=Information \
	--title=Rewiner)

}

if ! test -f "$WINEPREFIX/RewinderInstalled"; then
	( \
	# Initialize wineprefix
	wine cmd /c echo. > /dev/null
	# Install .NET 4.5
	winetricks -q dotnet45
	# Install DXVK
	winetricks -q dxvk
	# Download Austiblox ZIP and delete it if it already exists
	rm "AustibloxZIP.zip"
	wget "https://novetus.austiverse.com/Client/AustibloxZIP.zip"
	# Extract it
	unzip AustibloxZIP.zip -d "$WINEPREFIX/drive_c"
	# Enable sandbox
	winetricks sandbox
	# Rename it
	mv "$WINEPREFIX/drive_c/AustibloxZIP" "$WINEPREFIX/drive_c/Austiblox"
	# Run first installation process exe
	wine cmd /c "$WINEPREFIX/drive_c/Austiblox/Run me after extracting.bat"
	# Set variable for the old PWD
	OLDPWD="$PWD"
	# Run first install script
	cd "$WINEPREFIX/drive_c/Austiblox"
	wine "$(cat "$WINEPREFIX/drive_c/Austiblox/Run me after extracting.bat" | sed 's/start\s*/ /' | cut -c 2-)"
	# Make a file to indicate Austiblox is installed
	touch "$WINEPREFIX/RewinderInstalled" ) 2>&1 | loadscreen

	exit
fi

wine "$WINEPREFIX/drive_c/Austiblox/bin/AustibloxURI.exe" "$*"
